services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_SHARED_COOKIE=${RABBITMQ_SHARED_COOKIE}
    volumes:
      - "./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh:ro"
      - rabbitmq1-data:/var/lib/rabbitmq/
      - rabbitmq1-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_SHARED_COOKIE=${RABBITMQ_SHARED_COOKIE}
    volumes:
      - "./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh:ro"
      - rabbitmq2-data:/var/lib/rabbitmq/
      - rabbitmq2-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_SHARED_COOKIE=${RABBITMQ_SHARED_COOKIE}
    volumes:
      - "./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh:ro"
      - rabbitmq3-data:/var/lib/rabbitmq/
      - rabbitmq3-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq

  haproxy:
    image: haproxy:1.7
    container_name: haproxy
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672 # HTTP
      - 5672:5672   # AMQP
      - 1936:1936   # STATS
    networks:
      - rabbitmq

networks:
  rabbitmq:

volumes:
  rabbitmq1-data:
  rabbitmq1-logs:
  rabbitmq2-data:
  rabbitmq2-logs:
  rabbitmq3-data:
  rabbitmq3-logs:
